apiVersion: v1
kind: Service
metadata:
  name: zwave-js-ui
  labels:
    app: zwave-js-ui
spec:
  selector:
    app: zwave-js-ui
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
      name: http
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: websocket
  type: ClusterIP
